FROM ubuntu:20.04

COPY requirements_dev.txt .
COPY requirements.txt .

RUN apt update
RUN apt install -y python3.8 python3-pip
RUN pip install -r requirements_dev.txt
RUN pip install -r requirements.txt

RUN mkdir /stockeasy

WORKDIR /stockeasy

ENTRYPOINT [ "/bin/bash" ]
