FROM ubuntu:20.04

COPY requirements_dev.txt .

RUN apt update
RUN apt install -y python3.8 python3-pip
RUN pip install -r requirements_dev.txt

RUN mkdir /stockeasy

WORKDIR /stockeasy

ENTRYPOINT [ "/bin/bash" ]
