name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Update Packages
      run: apt update
    - name: Install Python
      run: apt install -y python3.8 python3-pip
    - name: Install Dev Requirements
      working-directory: /home/runner/work/stockeasy/stockeasy/
      run: pip install -r requirements_dev.txt
    - name: Build Distro
      working-directory: /home/runner/work/stockeasy/stockeasy/
      run: python3 setup.py sdist bdist_wheel