name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Update Packages
      run: sudo apt update
    - name: Install Python
      run: sudo apt install -y python3.8 python3-pip
    - name: Install Dev Requirements
      working-directory: /home/runner/work/stockeasy/stockeasy/
      run: pip install -r requirements_dev.txt
    - name: Build Distro
      working-directory: /home/runner/work/stockeasy/stockeasy/
      run: python3 setup.py sdist bdist_wheel
    - name: Upload Package to testPypi
      working-directory: /home/runner/work/stockeasy/stockeasy/
      env:
        PYPI_TEST_UID: ${{ secrets.TWINE_UID }}
        PYPI_TEST_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: twine upload --repository-url https://test.pypi.org/legacy/ dist/* -u TWINE_UID -p TWINE_PASSWORD
