name: CI
on: [push]
env:
  TOOL_DIRECTORY: /home/runner/work/stockeasy/stockeasy/
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Update Packages
      run: sudo apt update
    - name: Install Python
      run: sudo apt install -y python3.8 python3-pip
    - name: Install Dev Requirements
      working-directory: ${{env.TOOL_DIRECTORY}}
      run: pip install -r requirements_dev.txt
    - name: Build Distro
      working-directory: ${{env.TOOL_DIRECTORY}}
      run: python3 setup.py sdist bdist_wheel
    - name: Archive Version Info
      uses: actions/upload-artifact@v2
      with:
        name: version-info
        path: /home/runner/work/stockeasy/stockeasy/version_info.txt
    - name: Upload Package to testPypi
      working-directory: ${{env.TOOL_DIRECTORY}}
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_UID }}
        TWINE_PASSWORD : ${{ secrets.TWINE_PASSWORD }}
        TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
      run: twine upload dist/*
        
  test:
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
    - uses: actions/checkout@v1
    - name: Update Packages
      run: sudo apt update
    - name: Install Python
      run: sudo apt install -y python3.8 python3-pip
    - name: Install Wheel Requirements
      working-directory: ${{env.TOOL_DIRECTORY}}
      run: pip install -r requirements.txt
    - name: Download version info artifact
      uses: actions/download-artifact@v2
      with:
        name: version-info
        path: ${{env.TOOL_DIRECTORY}}
    - name: Install Stockeasy from testPyPi
      working-directory: ${{env.TOOL_DIRECTORY}}
      run: |
        VER_INFO=`cat version_info.txt`
        pip install --no-cache-dir --timeout 60 --index-url https://test.pypi.org/simple/ stockeasy==$VER_INFO
    - name: Pre-Production Testing
      working-directory: ${{env.TOOL_DIRECTORY}}
      run: echo "Testing Here"
  deploy:
    runs-on: ubuntu-20.04
    needs: [build, test]
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    - name: Update Packages
      run: sudo apt update
    - name: Install Python
      run: sudo apt install -y python3.8 python3-pip
    - name: Install Dev Requirements
      working-directory: ${{env.TOOL_DIRECTORY}}
      run: pip install -r requirements_dev.txt
    - name: Build Distro
      working-directory: ${{env.TOOL_DIRECTORY}}
      run: python3 setup.py sdist bdist_wheel
    - name: Upload Package to Pypi
      working-directory: ${{env.TOOL_DIRECTORY}}
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_UID }}
        TWINE_PASSWORD : ${{ secrets.TWINE_PASSWORD }}
      run: twine upload dist/*